### PR TITLE
Support JNLP security

### PR DESCRIPTION
**Pull request by kvish**
JIRA issues: DCOS_OSS-5063

### CODE REVIEW

**Review by jeschkies — COMMENTED** [review]
Looks good to me. Should we add tests?

Also, please add a proper pull request description with a `JIRA issues:` field. Here is a video of our commit format https://mesosphere.slack.com/archives/G7Y5Q786S/p1554982485236000.

**Comment by jeschkies** [comment]
Ping @kvish.

**Comment by kvish** [comment]
along with this we also need to have to plugin run under a valid jenkins user when security is enabled.  will hold off on merging this one until that is also merged

**Review by timcharper — APPROVED** [review]
Do we need to pass the single-use argument if JNLP is enabled?

(perhaps everything should just be single-use?)

**Pull request merged**
