### PR TITLE
Add local mvn repo containing usi artifacts

### PR DESCRIPTION
**Pull request by kvish**

### CODE REVIEW

**Comment by kvish** [comment]
created via local maven deploy:

Mesospheres-MacBook-Pro-4010:libs karanvishwanathan$ mvn deploy:deploy-file -Durl=file:///Users/karanvishwanathan/repos/mesos-plugin/repo -Dfile=usi-usi-0.1.jar -DgroupId=com.mesosphere -DartifactId=usi -Dpackaging=jar -Dversion=0.1

**Comment by kvish** [comment]
could remove USI artifacts from this PR and have people run the maven deploy above, thoughts?

**Review by kaiwalyajoshi — APPROVED** [review]
Go for binary blobs to get this started. Looks like we'll need to figure out how to release USI in the long-term which will need consensus from the team. Happy with this till USI's release process is sorted out.

**Review by jeschkies — DISMISSED** [review]
It's a neat idea but I'd like to understand if we really can refactor this plugin or should start from scratch and pull in what we need. What do you think about using Gradle for the build tool?

**Pull request merged**
